Repository magrathealabs/flipermercado, pull requests merged in 2019-09, with the labels that each got.

#12 Adicionar avatar do usuário na listagem
  Home.js
  components/index.js
  components/user-list/UserList.js
  components/user-list/index.js
  helpers/actions.js
Labels: enhancement

#11 Desabilitar botão de Comprar/Cancelar ao realizar uma compra
  components/confirmation/Confirmation.js
Labels: enhancement

#14 Lista de usuários com seções
  AppNavigator.js
  assets/logo.png
  components/confirmation/Confirmation.js
  components/confirmation/styles.js
  components/product-list/ProductList.js
  components/user-list/UserList.js
  components/user-list/styles.js
  helpers/alphabetic-grouping.js
Labels: help wanted

#19 Splash screen customizada
  AppNavigator.js
  Home.js
  app.json
  assets/splash.png
  components/confirmation/Confirmation.js
  components/index.js
  components/product-list/ProductList.js
  components/splash/Splash.js
  components/splash/index.js
  components/splash/styles.js
  components/user-list/UserList.js
Labels: visual

#22 Tema padrão
  App.js
  themes/default.js
Labels: visual

#30 Atualiza template das _issues_
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation
